### PR TITLE
Fix tooltip and remove compat build

### PR DESCRIPTION
**Pull request by dnlnashed**
This PR attempts to fix a couple of things

- Fix tooltips for the time slider and chapter menu
- Remove compat build used earlier for migrating vue 2 to vue 3

- - -
This change is [Reviewable](https://reviewable.io/reviews/yileifeng/story-ramp/10)

### CODE REVIEW

**Review by yileifeng — CHANGES_REQUESTED** [review]
To fix the tooltip styling, we need to: 
- add `import 'tippy.js/dist/tippy.css';` to main.ts
- also recommend applying the animation by adding`import 'tippy.js/animations/scale.css';` and `animation: 'scale'` when registering `VueTippy`, and then adding `animation: 'scale'` to the `v-tippy` directive to apply the animation

Can tinker with the other settings as needed to make transition look nice.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yileifeng/story-ramp/10#-:-Ncc3i5R0rN8BMc0VV7V:b-u680ss)* status: all files reviewed, 2 unresolved discussions (waiting on @dnlnashed)

___
*[`src/components/panels/map-panel.vue` line 152 at r1](https://reviewable.io/reviews/yileifeng/story-ramp/10#-Ncc3WhY7pSwQM0aj7a8:-Ncc3WhY7pSwQM0aj7a9:b-xywjku) ([raw file](https://github.com/yileifeng/story-ramp/blob/904ae0678ce5b35d67667f66a537184520450862/src/components/panels/map-panel.vue#L152)):*
> ```Vue
>                             });
>                     }
>                 }).use(i18n);
> ```

Looks like build failed from the formatting of this file, so make sure it is auto formatted properly.
___
*[`src/components/story/chapter-menu.vue` line 12 at r1](https://reviewable.io/reviews/yileifeng/story-ramp/10#-Ncc4IHP1hVOZZYDBBmF:-Ncc4IHP1hVOZZYDBBmG:b-qf1lb3) ([raw file](https://github.com/yileifeng/story-ramp/blob/9862be1ac05be969109c5953176396ade8d626cb/src/components/story/chapter-menu.vue#L12)):*
> ```Vue
>             
>             <button
>                 name="menu-button-tippy"
> ```

I think we can remove all instance of `menu-button-tippy` now?

**Review by dnlnashed — COMMENTED** [review]
Tooltip styling should now work, doneThanks

> *[Reviewable](https://reviewable.io/reviews/yileifeng/story-ramp/10#-:-NccbG4j6Gawfho2gWND:blpph83)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @yileifeng)

___
*[`src/components/panels/map-panel.vue` line 152 at r1](https://reviewable.io/reviews/yileifeng/story-ramp/10#-Ncc3WhY7pSwQM0aj7a8:-Nccb4C9E1tUQENwjWeI:bxdvf74) ([raw file](https://github.com/yileifeng/story-ramp/blob/904ae0678ce5b35d67667f66a537184520450862/src/components/panels/map-panel.vue#L152)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Looks like build failed from the formatting of this file, so make sure it is auto formatted properly.
</blockquote></details>

doneThanks
___
*[`src/components/story/chapter-menu.vue` line 12 at r1](https://reviewable.io/reviews/yileifeng/story-ramp/10#-Ncc4IHP1hVOZZYDBBmF:-Nccb1-gBUrNyYXugLP1:bxdvf74) ([raw file](https://github.com/yileifeng/story-ramp/blob/9862be1ac05be969109c5953176396ade8d626cb/src/components/story/chapter-menu.vue#L12)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

I think we can remove all instance of `menu-button-tippy` now?
</blockquote></details>

doneThanks

**Review by yileifeng — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yileifeng/story-ramp/10)* status: all files reviewed, 1 unresolved discussion (waiting on @dnlnashed)

**Review by yileifeng — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/yileifeng/story-ramp/10#-:-NccjYfl0BpE7QxRZHJp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dnlnashed)

___
*[`src/components/story/chapter-menu.vue` line 8 at r2](https://reviewable.io/reviews/yileifeng/story-ramp/10#-NccjfC3EYzS_u29YAho:-NccjfC3EYzS_u29YAhp:b-dk0qlt) ([raw file](https://github.com/yileifeng/story-ramp/blob/bb3842cf4c77991d2df5915feaab8f5df6b83c89/src/components/story/chapter-menu.vue#L8)):*
> ```Vue
>         <div class="flex items-center mt-4 mb-12">
>             <button
>                 name="menu-button-tippy"
> ```

also can remove these names as well

**Review by dnlnashed — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yileifeng/story-ramp/10)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`src/components/story/chapter-menu.vue` line 8 at r2](https://reviewable.io/reviews/yileifeng/story-ramp/10#-NccjfC3EYzS_u29YAho:-NccklzL0xXHyB2VWAZB:b-uimqhc) ([raw file](https://github.com/yileifeng/story-ramp/blob/bb3842cf4c77991d2df5915feaab8f5df6b83c89/src/components/story/chapter-menu.vue#L8)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

also can remove these names as well
</blockquote></details>

doneThanks

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yileifeng/story-ramp/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Pull request merged**
